// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetPlus_API.Data;

#nullable disable

namespace PetPlus.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250526172646_AddDataType")]
    partial class AddDataType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PetPlus_API.Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptedTerms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorporateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tbl_Clinica");
                });

            modelBuilder.Entity("PetPlus_API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ds_Acesso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ds_Bairro")
                        .HasColumnType("TEXT");

                    b.Property<string>("ds_CEP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ds_CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("ds_Cargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ds_Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("ds_Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ds_Email_Pessoal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ds_Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ds_Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ds_Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ds_RG")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("ds_Rua")
                        .HasColumnType("TEXT");

                    b.Property<string>("ds_Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ds_Usuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dt_DataContratacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dt_DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("nr_CRM")
                        .HasColumnType("TEXT");

                    b.Property<string>("nr_Numero")
                        .HasColumnType("TEXT");

                    b.Property<string>("nr_Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("tbl_Funcionarios");
                });

            modelBuilder.Entity("PetPlus_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rg")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("tbl_Usuarios");
                });

            modelBuilder.Entity("PetPlus_API.Models.Employee", b =>
                {
                    b.HasOne("PetPlus_API.Models.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("PetPlus_API.Models.User", b =>
                {
                    b.HasOne("PetPlus_API.Models.Clinic", "Clinic")
                        .WithMany("Users")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("PetPlus_API.Models.Clinic", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
